version: '3'
services:
  srsue0_5g_zmq:
    image: docker_srslte
    container_name: srsue0_5g_zmq
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .ue0-env
    environment:
      - COMPONENT_NAME=ue_5g_zmq
    expose:
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: 172.22.0.34
networks:
  default:
    external:
      name: docker_open5gs_default