{
 "title": "Open5Gs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "open5gs-upfd process memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "upf_memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UPF1 - Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF container memory MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "upf_memory_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMF auth reject",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fivegs_amffunction_amf_authreject",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF Container cpu usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "upf_cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "gNB count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "gnb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SMF1 UEs active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "ues_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "resident memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMF registration init success count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AMF auth reqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "fivegs_amffunction_amf_authreq", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MME - Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "enb_ue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UPF - GTP Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "fivegs_ep_n3_gtp_indatapktn3upf",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_ep_n3_gtp_outdatapktn3upf",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF session count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "amf_session", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MME - eNBs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "enb", "legendFormat": "__auto" }
   ]
  }
 ]
}