version: '3'
services:
    nr-eMBB-ue0:
        image: docker_ueransim
        container_name: nr-eMBB-ue0
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000000
            - NR_GNB_IP=172.22.0.23
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.50
    nr-eMBB-ue1:
        image: docker_ueransim
        container_name: nr-eMBB-ue1
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000001
            - NR_GNB_IP=172.22.0.23
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.51
    nr-eMBB-ue2:
        image: docker_ueransim
        container_name: nr-eMBB-ue2
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000002
            - NR_GNB_IP=172.22.0.23
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.52
    nr-URLLC-ue3:
        image: docker_ueransim
        container_name: nr-URLLC-ue3
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue2
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000003
            - NR_GNB_IP=172.22.0.23
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.53
    nr-URLLC-ue4:
        image: docker_ueransim
        container_name: nr-URLLC-ue4
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue2
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000004
            - NR_GNB_IP=172.22.0.23
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.54
    nr-URLLC-ue5:
        image: docker_ueransim
        container_name: nr-URLLC-ue5
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue2
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000005
            - NR_GNB_IP=172.22.0.23
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.55
networks:
    default:
        external:
            name: docker_open5gs_default
  