version: '3'
services:
    nr-eMBB-ue0:
        image: docker_ueransim
        container_name: nr-eMBB-ue0
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - ./:/mnt/voip
            - ../../venv:/mnt/venv
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000000
            - SST=1
            - SLICE_NAME=eMBB
            - NR_GNB_IP=172.22.0.23
            - ENTRY_POINT=/mnt/voip/video_streaming.sh
            - ENTRY_ARGS=https://www.youtube.com/watch?v=wkAp5x3Z_gc
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.50
    nr-URLLC-ue1:
        image: docker_ueransim
        container_name: nr-URLLC-ue1
        stdin_open: true
        tty: true
        volumes:
            - ./ueransim:/mnt/ueransim
            - ./:/mnt/voip
            - ../../venv:/mnt/venv
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - COMPONENT_NAME=ueransim-ue
            - MNC=01
            - MCC=001
            - UE_KI=8baf473f2f8fd09487cccbd7097c6862
            - UE_OP=11111111111111111111111111111111
            - UE_AMF=8000         
            - UE_IMEISV=4370816125816151
            - UE_IMEI=356938035643803
            - UE_IMSI=001010000000001
            - SST=2
            - SLICE_NAME=URLLC
            - NR_GNB_IP=172.22.0.23
            - ENTRY_POINT=/usr/bin/python3.10
            - ENTRY_ARGS=/mnt/voip/urllc_ue1.py
        expose:
            - "4997/udp"
        cap_add:
            - NET_ADMIN
        privileged: true
        networks:
            default:
                ipv4_address: 172.22.0.51
networks:
    default:
        external:
            name: docker_open5gs_default
  